name: compression

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@1.72.1
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Linting
        run: cargo clippy  -- -D warnings
      - name: Run tests
        run: cargo test --verbose
      - name: Generate code coverage
        run: cargo install cargo-tarpaulin && cargo tarpaulin --verbose --workspace
